### ISSUE TITLE
BSL-based shaders incompatible

### ISSUE THREAD

**Issue by lonadels** [cc-tweaked/CC-Tweaked#1080]
### Minecraft Version

1.18.x

### Version

1.100.5

### Details

Can see the sky and part of the world through the monitor with BSL-based shaders.
VBO option is **enabled** in config.

> ### ComplementaryShaders v4.4
> ![2022-04-29_04 50 12](https://user-images.githubusercontent.com/15861168/165873728-2d3a5e2e-421c-42ac-90b9-4a04cd155f6f.png)

> ### BSL v8.1.02.2
> ![2022-04-29_04 50 19](https://user-images.githubusercontent.com/15861168/165873734-725eb4f7-07e2-48a8-9b9f-48a0f1dfb38d.png)

**Comment by lonadels** [comment]
# Solution for BSL
* Change `Fast Render` option to ``False`` in **Video Settings > Performance**.

## But...
**Complementary** still has some problems - the sky see through the borders.
> ### ComplementaryShaders v4.4
> ![2022-04-29_05 06 13](https://user-images.githubusercontent.com/15861168/165874940-13ae81dd-e2ae-48d8-81bb-dcd9a0ae82e4.png)

**Comment by SquidDev** [comment]
I'm afraid shaders are not supported by CC:T. Rendering issues are hard to debug at the best of times, and adding adding shaders and Optifine into the mix makes things basically impossible to debug, especially due to their closed-source nature.

I've spent a lot of hours trying to fix issues with shaders in the past, and it rarely comes to anything. I'm afraid I just can't justify any more time on this sort of stuff.

**Comment by boxhats** [comment]
change monitor_renderer = "BEST" to monitor_renderer = "VBO" in Minecraft\Instances\[pack you're playing]\config 
computercraft-client.toml

I am using complimentary shaders and this worked for me.

**Comment by tt-thoma** [comment]
Found out on reddit: https://www.reddit.com/r/Optifine/comments/m5sf83/comment/gr4g6fw/
CC:Tweaked is maybe conflicting with the BSL/Optifine "pipeline"
