### ISSUE TITLE
A grand-ol' cleanup 

### ISSUE THREAD

**Issue by SquidDev** [cc-tweaked/CC-Tweaked#658]
A continuation of #91 for the modern age. Can't believe we're 550 issues later...

 - [x] Go through all times we request a block update, and see if we can narrow the scope. We don't actually need to mark the chunk as dirty a lot of the times.

   This was, in part at least, responsible for #643 (turtles shouldn't be doing block updates when reading NBT!).
 -  [ ] Clean up "on destroyed" hooks for blocks (i.e. modems). I feel there's a couple of places we could get away with using `removed`. Likewise, could we rebuild the state when validated?
 - [x] Remove all the `m_` prefixes. So petty I know, and going to cause merge conflicts. But currently we're horrifically inconsistent.
 - [x] Investigate using Mojang mappings. Should make the job of Fabric people easier, but a) need to check legal terms and b) see how well FG copes with it.
 - [x] Reformat everything to use single-line braces and no spaces around parens. Undecided on this, but would mean IDEA can cope with switch expressions in a sensible way.
 - [x] Look into what network packets block updates send. I'm fairly sure most blocks (peripherals especially) don't need to send as much now.

**Comment by Ronan-H** [comment]
Hey, would you accept PRs just refactoring random parts of the codebase against this issue? I want to contribute to this project somehow but I'm reluctant about learning all about forge modding because it looks like such a complicated ecosystem.

Just to pick a random example, in [TextBuffer.java](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.15.x/src/main/java/dan200/computercraft/core/terminal/TextBuffer.java), we have:
- lots of duplicated code in constructors and elsewhere. Instead we can use `this()` or create new functions maybe, assuming the constructor overloads are actually being used
- [redundant code](https://github.com/SquidDev-CC/CC-Tweaked/blob/66e42e0817484702d3be7ab880e60246097f7ecb/src/main/java/dan200/computercraft/core/terminal/TextBuffer.java#L94):

```Java
end = Math.min( end, pos + text.length() );
end = Math.min( end, this.text.length ); // overwrites the prev line with no side effects, right?
```

Hope I'm right about those, I'm quite rusty with Java at this point.

**Comment by Ronan-H** [comment]
> I don't think this one is correct - end is reused within the next Math.min call, so we do use the intermediate value. It looks like this ensures end is less than the buffer's width and the text's length.

Oops. That one just looked weird to me at a glance.

Would writing tests be a better way of getting familiar to the project? At least that carries no risk of breaking anything :) Going off topic we can always create a new issue if necessary.

**Comment by SquidDev** [comment]
I wouldn't worry too much about breaking things too much. Most of the time I (or tests) catch things - it's just a few complex bits which can break in very subtle ways... 

That said, definitely not going to complain about more tests. We do [track coverage](https://codecov.io/gh/SquidDev-CC/CC-Tweaked/tree/mc-1.15.x/src/main/java/dan200/computercraft/core), which should give an idea of what code _isn't run_ (not the same as not tested :p).

There's a bit of info in CONTRIBUTING.md about how things are tested, though if you're sticking to non-Forge related code you probably don't need to worry too much.
