### ISSUE TITLE
[API Addition]Add getType to GenericSource

### ISSUE THREAD

**Issue by Seniorendi** [cc-tweaked/CC-Tweaked#830]
I saw that generic peripherals does use the ResourceLocation for the type. I would request to change this, like with `getType` in `IPeripheral`.

**Comment by Seniorendi** [comment]
Because I want to change my [proxy system](https://docs.srendi.de/peripheralproxy/getstarted/) to a generic system, I want to ensure that older programs will work with the new system. 
I know, that modding takes some time and that everyone has a reallife. I just want to ask, when could this feature be expected?

**Comment by SquidDev** [comment]
> I just want to ask, when could this feature be expected?

Not clue I'm afraid. Hopefully next release, but I genuinely don't know how hard this'll be to implement.

Given this and #839, we probably need a priority system too for generic peripherals, so there's some determinism in which methods are chosen. But then we get into the same issues as https://github.com/dan200/ComputerCraft/issues/153, which I really wanted to avoid.

**Comment by Seniorendi** [comment]
I had an Idea. I could create a class which implements `IPerpiheralProvider` to register my peripherals for other blocks.
I will try that, would maybe be a better way

**Comment by SquidDev** [comment]
Only took 5 months! Release is still a while away, so open to feedback on the API, etc...

I think the plan long-term is to allow `peripheral.getType` to return multiple values, effectively primary type (i.e. `disk`, `minecraft:chest`) plus additional traits (`inventory`), effectively allowing you to do things like `peripheral.find("inventory")` instead of the current mess of things.
